# Generated by Django 4.2.6 on 2023-11-29 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('body', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Создан')),
                ('publication', models.BooleanField(default=False, verbose_name='опубликован')),
                ('views_count', models.BigIntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('title',),
            },
        ),
    ]
