# Generated by Django 4.2.6 on 2023-10-19 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_data_at_created',
            field=models.DateField(default=datetime.date.today, verbose_name='на удаление'),
        ),
    ]
