# Generated by Django 4.2.6 on 2024-01-13 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('product_is_publicated', 'Can publish product'), ('description', 'Can edit description'), ('category', 'Can change category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='data_change',
            field=models.DateField(default=datetime.date.today, verbose_name='последнее изменение'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_is_publicated',
            field=models.BooleanField(default=False, verbose_name='опубликован'),
        ),
    ]
